- server:
    remoteSource: ~/docker/apache/app/minestatus/public/products
    host: 52.26.27.120
    privateKey: id_rsa
    username: ubuntu
    localDestination: products
- server:
    remoteSource: ~/docker/apache/app/minestatus/public/members
    host: 52.26.27.120
    privateKey: id_rsa
    username: ubuntu
    localDestination: members